---
- name: install nginx
  hosts: all
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
